### ISSUE TITLE
使用内存数据库，消息接收到很多次，是这样的吗

### ISSUE THREAD

**Issue by 810961186** [dotnet-shashlik/shashlik.eventbus#1]

**Comment by 810961186** [comment]
有群吗，想跟您学习下

**Comment by 280780363** [comment]
> 有群吗，想跟您学习下

是有可能会收到多次的,暂时没有群哦,本项目文档推广这些还不全.

**Comment by sgf** [comment]
> > 有群吗，想跟您学习下
> 
> 是有可能会收到多次的,暂时没有群哦,本项目文档推广这些还不全.

提一嘴，.net 中还是有不少很强的 pub/sub 库的,支持tcp。

https://github.com/Cysharp/MessagePipe
