### ISSUE TITLE
考虑支持NATS总线吗？

### ISSUE THREAD

**Issue by lable** [dotnet-shashlik/shashlik.eventbus#2]

**Comment by 280780363** [comment]
这个没有用过呢，所以没有集成计划，您如果熟悉NATS总线，可以提交PR。

**Comment by sgf** [comment]
> _No description provided._

@280780363  NATS 应该是跨语言(go)了，如有集成计划，有开源的客户端库（性能很强的那种） https://github.com/Cysharp/AlterNats。

但是个人是我不建议集成，先好好做好.net的内循环再说。
